name: Build & Push to ACR
on:
  workflow_dispatch:

env:
  IMAGE_NAME: philos-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login to ACR (admin user)
        uses: docker/login-action@v3
        with:
          registry: acrphilostest.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            acrphilostest.azurecr.io/${{ env.IMAGE_NAME }}:latest
            acrphilostest.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
